version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
- cmd: msbuild /t:Restore src\NLog.Extensions.AzureStorage.sln /p:Configuration=Release /verbosity:minimal
- cmd: msbuild /t:Pack src\NLog.Extensions.AzureStorage /p:Configuration=Release /verbosity:minimal
- cmd: msbuild /t:Pack src\NLog.Extensions.AzureEventHub /p:Configuration=Release /verbosity:minimal
- cmd: dotnet test src\NLog.Extensions.AzureEventHub.Tests /p:Configuration=Release --verbosity minimal

artifacts:
- path: '**\NLog.Extensions.AzureStorage*.nupkg'
- path: '**\NLog.Extensions.AzureEventHub*.nupkg'