version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore src\NLog.Extensions.AzureStorage.sln
build:
  verbosity: minimal
after_build:
- cmd: >-
    mkdir NLog.Extensions.AzureStorage\lib\net45

    xcopy src\NLog.Extensions.AzureStorage\bin\Release\NLog.Extensions.AzureStorage.dll NLog.Extensions.AzureStorage\lib\net45 /y

    xcopy nuget\NLog.Extensions.AzureStorage.nuspec NLog.Extensions.AzureStorage /y


    nuget pack NLog.Extensions.AzureStorage\NLog.Extensions.AzureStorage.nuspec
artifacts:
- path: '**\NLog.Extensions.AzureStorage.nupkg'