version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

before_build:
- cmd: msbuild /t:Restore,Pack src\NLog.Extensions.AzureStorage

artifacts:
- path: '**\NLog.Extensions.AzureStorage*.nupkg'